#:schema node_modules/wrangler/config-schema.json
name = "storage-state"
main = "src/index.ts"
compatibility_date = "2024-08-06"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
    { binding = "typeauth_keys", id = "9744321d80574d39a97f2b82416e9951", preview_id = "9744321d80574d39a97f2b82416e9951" },
]

durable_objects.bindings = [
    { name = "RATELIMIT", class_name = "RateLimit" },
    { name = "REMAIN", class_name = "Remain" },
]

[[migrations]]
tag = "v1"
new_classes = ["RateLimit"]

[[migrations]]
tag = "v2"
new_classes = ["Remain"]
